In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import datasets
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


-  Dados da base Iris

In [3]:
iris = datasets.load_iris()
Xiris = pd.DataFrame(iris.data, columns=iris.feature_names)
yiris = pd.Series(pd.Categorical.from_codes(iris.target, iris.target_names))
X_trainIris, X_testIris, y_trainIris, y_testIris = train_test_split(Xiris.values, yiris.values, random_state=1, test_size=0.30)
X_trainIris,y_trainIris

(array([[7.7, 2.6, 6.9, 2.3],
        [5.7, 3.8, 1.7, 0.3],
        [5. , 3.6, 1.4, 0.2],
        [4.8, 3. , 1.4, 0.3],
        [5.2, 2.7, 3.9, 1.4],
        [5.1, 3.4, 1.5, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [7.7, 3.8, 6.7, 2.2],
        [6.9, 3.1, 5.4, 2.1],
        [7.3, 2.9, 6.3, 1.8],
        [6.4, 2.8, 5.6, 2.2],
        [6.2, 2.8, 4.8, 1.8],
        [6. , 3.4, 4.5, 1.6],
        [7.7, 2.8, 6.7, 2. ],
        [5.7, 3. , 4.2, 1.2],
        [4.8, 3.4, 1.6, 0.2],
        [5.7, 2.5, 5. , 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [4.8, 3. , 1.4, 0.1],
        [4.7, 3.2, 1.3, 0.2],
        [6.5, 3. , 5.8, 2.2],
        [4.6, 3.4, 1.4, 0.3],
        [6.1, 3. , 4.9, 1.8],
        [6.5, 3.2, 5.1, 2. ],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 2.8, 4.5, 1.3],
        [6.7, 3.3, 5.7, 2.5],
        [6. , 3. , 4.8, 1.8],
        [5.1, 3.8, 1.6, 0.2],
        [6. , 2.2, 4. , 1. ],
        [6.4, 2.9, 4.3, 1.3],
        [6.5, 3. , 5.5, 1.8],
        [5. , 2.3, 3.3, 1. ],
        [6

- Treinamento e acurácia

In [4]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.5, max_depth=3, random_state=1)
clf.fit(X_trainIris, y_trainIris)
ypredict = clf.predict(X_testIris)

In [5]:

accuracy_score(y_testIris, ypredict)*100

97.77777777777777

- BAse de dados breast_cancer

In [11]:
cancer = datasets.load_breast_cancer()
Xcancer = pd.DataFrame(cancer.data, columns=cancer.feature_names)
ycancer = pd.Series(pd.Categorical.from_codes(cancer.target, cancer.target_names))
Xcancer, ycancer
X_trainCancer, X_testCancer, y_trainCancer, y_testCancer = train_test_split(Xcancer.values, ycancer.values, random_state=1, test_size=0.30)
X_trainCancer,y_trainCancer

(array([[1.152e+01, 1.493e+01, 7.387e+01, ..., 9.608e-02, 2.664e-01,
         7.809e-02],
        [1.305e+01, 1.931e+01, 8.261e+01, ..., 1.111e-02, 2.439e-01,
         6.289e-02],
        [1.420e+01, 2.053e+01, 9.241e+01, ..., 1.339e-01, 2.534e-01,
         7.858e-02],
        ...,
        [1.720e+01, 2.452e+01, 1.142e+02, ..., 1.899e-01, 3.313e-01,
         1.339e-01],
        [1.403e+01, 2.125e+01, 8.979e+01, ..., 7.963e-02, 2.226e-01,
         7.617e-02],
        [1.303e+01, 1.842e+01, 8.261e+01, ..., 5.013e-02, 1.987e-01,
         6.169e-02]]),
 ['benign', 'benign', 'benign', 'benign', 'benign', ..., 'malignant', 'benign', 'malignant', 'benign', 'benign']
 Length: 398
 Categories (2, object): ['malignant', 'benign'],
      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
 0          17.99         10.38          122.80     1001.0          0.11840   
 1          20.57         17.77          132.90     1326.0          0.08474   
 2          19.69         21.25 

- Treinamento e acurácia

In [8]:
clf = GradientBoostingClassifier(n_estimators=90, learning_rate=0.70, max_depth=3, random_state=1)
clf.fit(X_trainCancer, y_trainCancer)
ypredict = clf.predict(X_testCancer)

#accuracy_score(y_testCancer, ypredict)*100
X_testCancer

array([[1.469e+01, 1.398e+01, 9.822e+01, ..., 1.108e-01, 2.827e-01,
        9.208e-02],
       [1.317e+01, 1.866e+01, 8.598e+01, ..., 2.088e-01, 3.900e-01,
        1.179e-01],
       [1.295e+01, 1.602e+01, 8.314e+01, ..., 1.056e-01, 3.380e-01,
        9.584e-02],
       ...,
       [1.578e+01, 1.789e+01, 1.036e+02, ..., 1.810e-01, 3.792e-01,
        1.048e-01],
       [1.287e+01, 1.621e+01, 8.238e+01, ..., 5.780e-02, 3.604e-01,
        7.062e-02],
       [1.116e+01, 2.141e+01, 7.095e+01, ..., 4.306e-02, 2.976e-01,
        7.123e-02]])